Implement error check for test output
Add error handling for test output in CI workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,9 +17,11 @@ jobs:
         - name: Run testing
           run: |
             output=$(node dist/Test1.js)
-            echo "$output"
-            
 
+            if [ $output -ne 0 ]; then
+              echo "error $output"
+              exit 1
+            fi
 
 
 
